fix: remove `matchedDN` and `diagnosticMessage` from `SearchResponseEntry`
jimlambrt/gldap pull request #58
Opened 2023-12-20 20:25 UTC by xunleii

Hi, 

Firstly, thanks for this library, I'm using it to create my own LDAP server.

This PR removes `matchedDN` and `diagnosticMessage` from `SearchEntryResponse` because they should not be found here.

> ```
> SearchResultEntry ::= [APPLICATION 4] SEQUENCE {
>      objectName      LDAPDN,
>      attributes      PartialAttributeList }
> 
> PartialAttributeList ::= SEQUENCE OF
>        partialAttribute PartialAttribute
> 
> LDAPDN ::= LDAPString
>            -- Constrained to  [RFC4514]
> 
> LDAPString ::= OCTET STRING -- UTF-8 encoded,
>               -- [ISO10646] characters
> 
> PartialAttribute ::= SEQUENCE {
>      type       AttributeDescription,
>      vals       SET OF value AttributeValue }
> 
> AttributeDescription ::= LDAPString
>            -- Constrained to
>            -- [RFC4512]
> 
> AttributeValue ::= OCTET STRING
> ```
> source: https://ldap.com/ldapv3-wire-protocol-reference-search/,

2023-12-23 18:00 UTC, jimlambrt commented
If there's no rush and you don't mind: I'll take a look after the holiday.

2023-12-24 01:05 UTC, xunleii commented
Yes, of course! 😄

Happy holidays and Merry Christmas!

2024-01-03 13:49 UTC, jimlambrt requested changes
This looks great.  Would you mind rebase on main so CI will be happy before we approve and merge?

2024-01-06 21:36 UTC, jimlambrt commented
@xunleii I know things are always busy after the holidays, but I'm just following up about rebasing this so we can merge it.

2024-01-06 21:57 UTC, xunleii commented
> @xunleii I know things are always busy after the holidays, but I'm just following up about rebasing this so we can merge it.
> 

Hi, sorry, I've seen your message but totally forgot just after.
I'll try to do that as soon as possible (this night or tomorrow)

Thanks for the reminder 😄

2024-01-15 18:42 UTC, merged